### ISSUE TITLE
Feature Request - Add a confirmation password field when changing the password

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#1]
**Changing password - Retype new password**

It could be a problem for the users to type the new password just once, as a lot of mistakes could go unnoticed.

A second field with validation for retyping new password can prevent unnoticed mistakes. An alternative could be an email conformation of changed password with the new one written, but this could create security issues. 

When typing new password, a user can make a mistake that gets unnoticed by them (like type it in all caps, make a spelling mistake, duplicate a symbol or miss it). A good way to prevent that would be to add a second field for new password and validation that the input in both fields is matching.

**Comment by duy-a** [comment]
Released into private alpha testing v0.4

**Comment by vpeycheva** [comment]
Just tested it on the alpha web app. It works as expected and I'll close the task.
