### ISSUE TITLE
Dark mode dates and notes not visible

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#10]
**Description**
When in dark mode, dates and notes such as "With due date " have white background and white text

**To Reproduce**
1. Open app (alpha web or android) 
2. Turn on dark mode
3. Click on "Today", "Next 7 Days" or "All todos"

**Expected behavior**
For notes and to have black background and white text.
![Screenshot from 2020-05-19 11-40-58](https://user-images.githubusercontent.com/65238833/82304951-aee3e780-99c5-11ea-8bfd-0a7f6379e16a.png)
(Screenshot from beta web app)

**Actual Behavior**
Notes and dates have white background and white text

**Screenshots**
![Screenshot from 2020-05-19 11-35-14](https://user-images.githubusercontent.com/65238833/82305102-e5b9fd80-99c5-11ea-9512-1e3c279a02f6.png)
![Screenshot from 2020-05-19 11-34-41](https://user-images.githubusercontent.com/65238833/82305112-e8b4ee00-99c5-11ea-88ff-a1a8fa0a719a.png)
![Screenshot from 2020-05-19 11-31-29](https://user-images.githubusercontent.com/65238833/82305132-eeaacf00-99c5-11ea-9015-1314ec0b28b5.png)

**Desktop:**
 - Ubuntu 18.04 Bionic Beaver
 - Mozilla Firefox
 - Version 76.0.1 (64-bit)

**Smartphone:**
 - Nokia 6.1
 - Android 10
 - Browser - not using browser

**Comment by duy-a** [comment]
A fix has been released to alpha web & android version. Please assist to verify and close the issue if expected behavior is met.

**Comment by vpeycheva** [comment]
It's fixed
