### ISSUE TITLE
Feature Request - When date is chosen and you click +, the task to be automaticly created for that date

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#11]
When I select a date in the "Next 7 Days" and click +, the task is created for today, not the chosen date.

**Solution**
When the user has chosen a particular day, while looking at their schedule,  and they click + button, the task to be created with that date on default.

**Additional context**
![vokoscreen-2020-05-19_15-52-40](https://user-images.githubusercontent.com/65238833/82330173-25471080-99eb-11ea-9379-1c7068e47203.gif)

**Comment by duy-a** [comment]
A fix has been released to alpha web & android version. Please assist to verify and close the issue if expected behavior is met.

**Comment by vpeycheva** [comment]
It works as expected.
