### ISSUE TITLE
For review - No limit on task notes - Very low priority and severity

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#13]
**Description**
There is no limit on the notes.

**To Reproduce**
1. Open app  (It will be easier in web app)
2. Click on +
3. Start writing. I find it easier to choose a word and copy it a bunch of times
4. Paste word until bored.
5. Copy all from the field and paste in a text editor that can show you how many characters you have selected

**Expected behavior**
Limit between 1 000 and 10 000 characters.

**Actual behavior**
There is no limit for the field. I got to almost 1 000 000 characters or over 180 pages of text.

**Screenshots**

![Screenshot from 2020-05-19 18-00-08](https://user-images.githubusercontent.com/65238833/82343752-e79eb380-99fb-11ea-99aa-bbaea42ec1b8.png)

![Screenshot from 2020-05-19 18-00-23](https://user-images.githubusercontent.com/65238833/82343621-c342d700-99fb-11ea-9dbe-ff0839eab576.png)

![Screenshot from 2020-05-19 18-07-07](https://user-images.githubusercontent.com/65238833/82343605-c047e680-99fb-11ea-888f-b5e5f240f9f6.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Mozilla Firefox
 - 76.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Nokia 6.1
 - Android 10

**Additional context**
I do not know if this is a problem or not, just seems logical to have a limit on every field.

**Comment by duy-a** [comment]
A fix has been released to alpha web & android version. Please assist to verify and close the issue if expected behavior is met. Now limit to 5,000 characters

**Comment by vpeycheva** [comment]
Works with up to 5 000 symbols
