### ISSUE TITLE
When you flip through the dates in page 'Next 7 days' information about tasks to that weeks does not update

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#15]
**Describe the bug**
When you flip through the dates in page 'Next 7 days', information about tasks to that weeks does not update. You see tasks only for current week. To update the information to that week that you open you should choose any day from the list of that week.

**To Reproduce**
1. Open web app
2. Open folder 'Next 7 days'
3.  Flip through the dates
4. Current week's tasks are still open
5. Press to  06.29.2020
6. Information about week tasks is updated

**Expected behavior**
Updating tasks while flipping through the dates (weeks).
![2](https://user-images.githubusercontent.com/65408344/82358025-e5c0fa00-99d3-11ea-8fc8-fb9df38b3819.jpg)
![3](https://user-images.githubusercontent.com/65408344/82358031-e8bbea80-99d3-11ea-8eb7-24c061aa8bb1.jpg)

**Screenshots**

**Desktop:**
 - OS: Windows 10 home
 - Browser Chrome 
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by duy-a** [comment]
I will have to collect more data regarding the proposal before implementing the change

**Comment by Viktoriia-Chumak** [comment]
There is also the same situation when you flip through the dates in page 'Next 7 days' (for example 6-12 July 2020), go to another folder such as 'Today', 'Inbox' or 'All todos' and return to 'Next 7 days'.
You see tasks only for current week on the bottom of the page, and days of week that you flip through for example 6-12 July 2020 on the top. 
But if you update the page 'Next 7 days' it displays current week on the top.
I think this information should updates after returning to  'Next 7 days' from other folders immediately.
