### ISSUE TITLE
Feature request - Next 7 Days - name is not appropriate - low priority

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#17]
**Description:**
When I think about the next 7 days I think about today the literal 6 days after that. When I open the page I see this week, Monday to Sunday, regardless of which day it currently is, and a possibility to navigate tasks by weeks

**Suggestion**
A more suitable name would be Week

**Comment by duy-a** [comment]
The above sections shows the week (you can consider it as a mini calendar by week). While the tasks are actually starting as you expect, today + 6 days after that. The start of the list will always be today or the day you have selected.

Open for a further discussion

**Comment by duy-a** [comment]
Released into private alpha testing v0.4. Has been renamed to "Week Planning"
