### ISSUE TITLE
Title can be just space

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#18]
**Description**
Space alone can be title for a task

**To Reproduce**
1. Open app
2. Click on +
3. Input one or more empty spaces by clicking the space bar 
4. Click the save button

**Expected behavior**
Error message "Title can not be empty" is displayed

**Actual behavior**
Task is successfully saved 

**Screenshots**
![vokoscreen-2020-05-20_12-41-23](https://user-images.githubusercontent.com/65238833/82433017-7f9eaa80-9a99-11ea-8676-d81d35741183.gif)

**Desktop**
 - Ubuntu 18.04
 - Mozilla Firefox
 - 76.0.1 (64-bit)

**Smartphone:**
 - Nokia 6.1
 - Android 10

**Comment by duy-a** [comment]
A fix has been released to alpha web & android version. Please assist to verify and close the issue if expected behavior is met.

**Comment by vpeycheva** [comment]
The expected behavior is met
