### ISSUE TITLE
Possibility to slide dates only by pressing left mouse button 

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#19]
**Describe the bug**
It is impossible to slide dates (when it is adding to task) by scroll wheel (of mouse). It is possible only by pressing left mouse button and move it up and down. 

**To Reproduce**
1. Open Web app
2. Press '+' to add task
3. Open 'Due date' section
4. Scroll mouse wheel up and down
5. You couldn't choose a date

**Expected behavior**
Possibility to slide dates by scrolling mouse wheel up and down.

**Desktop**
OS: Windows 10 home
Browser Chrome
Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by duy-a** [comment]
have replaced with the calendar view, so it will be easier to select the date. The update has been released to the alpha version. Please assist to verify.

**Comment by Viktoriia-Chumak** [comment]
Calendar view works correctly.
