### ISSUE TITLE
Adding section 'Overdue' to 'All todos' folder

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#20]
**Describe the solution you'd like**
It will be better for visual separation tasks list, if folder 'All todos' has section 'Overdue' as 'Today' folder. 
![Untitled](https://user-images.githubusercontent.com/65408344/82478674-40735800-9a9f-11ea-96d5-c17e5f260bf5.jpg)
![Untitled1](https://user-images.githubusercontent.com/65408344/82478681-410bee80-9a9f-11ea-83b7-f6be088f3c81.jpg)

**Comment by duy-a** [comment]
have added the overdue section and released in alpha version. Please assist to verify.

Thank you :)

**Comment by Viktoriia-Chumak** [comment]
It works. Thank you.
