### ISSUE TITLE
Date and name of the day which has tasks should become bold. 

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#21]
**Describe the solution you'd like**
It would be much more comfortable for visualization, if the days which have tasks become bold in section 'Next 7 days'.
![1](https://user-images.githubusercontent.com/65408344/83444321-39423780-a419-11ea-8355-3596fcc420f4.jpg)

**Comment by duy-a** [comment]
Released into private alpha testing v0.4 (will display the number of task for the day)
