### ISSUE TITLE
Feature request - Ability to manualy write time for reminder - Mobile app

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#22]
When adding a task with reminder on the mobile app it seems like too much effort to go from current time to the desired time. For example if you want to set an reminder to do something i 6 am and and the current time is 18:50 you have to click a lot of times to set it.

**Describe the solution you'd like**
It would be convenient to have the ability to click on the field and write the desired time.

**Comment by duy-a** [comment]
Released into private alpha testing v0.4

**Comment by vpeycheva** [comment]
I'll close this one, but there is a bug:
https://github.com/duy-a/tobidun-issues/issues/26
