### ISSUE TITLE
No symbol limit for category name - Very Low Priority

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#23]
**Describe**
There is no symbol limit for category name. I believe that no more than 180 symbols are needed for it.

**To Reproduce**
1. Open app.tododone.io
2. Click on "Categories"
3. Click on "+ ADD"
4. Input as many symbols as you want

**Expected behavior**
The limit to be around 180 max

**Actual behavior**
There is no limit for the input. When the symbols are too many, the text is not visible.

**Screenshots**
![vokoscreen-2020-06-29-18-34-37](https://user-images.githubusercontent.com/65238833/86026433-17e46380-ba38-11ea-82fd-be9e0a0b65e5.gif)

**Desktop:**

- Ubuntu 18.04
- Mozilla Firefox
- 77.0.1 (64-bit)

**Smartphone:**
I have not reproduced on mobile for now,.

**Additional information:**
This may not be overwhelming for the software of the servers, but some users with older phones may experience some difficulties. For example is you believe you've copied a small amount of text, but it happens to be a really long text, your phone may freeze and require restarting to function normally. I managed to paste over 500 000 symbols.

**Comment by duy-a** [comment]
released to alpha, character limit to 70
