### ISSUE TITLE
Categories not visible when creating task

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#24]
**Describe the bug**
Categories are not visible when creating task. The only one that can be used is "priority 1", that I have not created. Eved creating new categories while creating tasks does noting.

**To Reproduce**
1. Open app
2. Create new task or edit an existing one
3. Click on category button while editing task
4. Try to choose a category
5. Try creating a category

**Expected behavior**
1. For the already created categories to be visible
2. Creating a new category, while editing a task, should add connect the category and task
3. For the "priority 1" category to not exist when it is not created by the user

**Actual behavior** 
1. Created categories are not visible in tasks
2. Creating new category, while editing a task, does not connect them, nor does it make choosing the new one possible.
3. Only category that can be chosen is "priority 1" which I have not created.

**Screenshots**
![vokoscreen-2020-06-29-19-09-32](https://user-images.githubusercontent.com/65238833/86030672-719b5c80-ba3d-11ea-84c5-4af921aa04bc.gif)

**Desktop:**
 - Ubuntu 18.04
 - Mozilla Firefox
 - 77.0.01 (64 bit)

**Smartphone:*
Have not tested yet, will update as soon as it's available.

**Comment by duy-a** [comment]
A hot fix has been released on both web & android

**Comment by vpeycheva** [comment]
I just retested it. The bug is fixed and everything seems to work fine.
