### ISSUE TITLE
Dark mode setting not remembered

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#25]
**Describe the bug**
When app is opened (after dark mode has already been chosen) the app starts in light mode. Then when settings is clicked, the dark mode is initiated.

**To Reproduce**
1. Open app and turn dark mode on
2. Open app again (in new window or on mobile)
3. The app starts in light mode
4. Click on settings (and dark mode is automatically turned on) 

**Expected behavior**
If dark mode is chosen, every time it is openen it is the chosen mode.

**Actual behavior**
When app is opened (in alpha & beta web, as well as mobile) it is in light mode. The only after you click on setting, it is automatically turned on.

**Screenshots**
![vokoscreen-2020-06-29-21-19-13](https://user-images.githubusercontent.com/65238833/86042146-66512c80-ba4f-11ea-8aaa-5e865cfa3e27.gif)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Mozilla Firefox
 - 77.0.1 (64 bit)

**Smartphone (please complete the following information):**
 - Nokia 6.1
 - Android 10

**Comment by duy-a** [comment]
fix has been released for both web & android
