### ISSUE TITLE
Presence of left side panel on the screen after pressing to settings button of 'Categories' or 'Tags'

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#27]
**Describe the bug**
There is problem with automatic hiding of side panel. Left side panel with menu should hides automatically after pressing to settings button of 'Categories' or 'Tags'.  But it stays open

**To Reproduce**
1. Open app
2. Slide from the left to the right to open menu
3. Press settings button on section 'Categories'
4. Tasks are sorted, but side panel with menu didn't hide automatically
5. Slide from the right to the left to hide the panel to watch sorted tasks
6. Press settings button on section 'Tags'
7. Tasks are sorted, but side panel with menu didn't hide automatically
8. Slide from the right to the left to hide the panel to watch sorted tasks

**Expected behavior**
Left side panel with menu should hides automatically after sorting tasks by tags and categories.

**Screenshots**
![step1](https://user-images.githubusercontent.com/65408344/86161386-2df73000-badb-11ea-9f0f-c44077adedc2.jpg)
![step2](https://user-images.githubusercontent.com/65408344/86161401-32bbe400-badb-11ea-881e-3f5b61880b23.jpg)
![step3](https://user-images.githubusercontent.com/65408344/86161390-2fc0f380-badb-11ea-95a2-89508376de43.jpg)
![step4](https://user-images.githubusercontent.com/65408344/86161404-33ed1100-badb-11ea-8609-6c92b03c044f.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - OS: Android 9.

**Comment by duy-a** [comment]
fix has been released to web & android
