### ISSUE TITLE
No possibility to edit or delete tags or categories

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#28]
**Describe the bug**
There is impossible to edit or delete tags or categories in appropriate sections. Settings button doesn't work although it is clickable.

**To Reproduce**
1. Open app
2. Slide from the left to the right to open menu
3. Press settings button on section 'Categories'
4. Hide the panel to watch sorted tasks
5. Press settings button to edit or delete each category
6. Nothing happens
7. Slide from the left to the right to open menu
8. Press settings button on section 'Tags'
9. Hide the panel to watch sorted tasks
10. Press settings button to edit or delete each tag
11. Nothing happens

**Expected behavior**
Settings button should work and have menu with possible action 'Edit' and 'Delete'.

**Screenshots**
![Screenshot_20200630_141716_io tobidun app](https://user-images.githubusercontent.com/65408344/86163062-bbd41a80-badd-11ea-9512-6e076e81b544.jpg)
![Screenshot_20200630_141725_io tobidun app](https://user-images.githubusercontent.com/65408344/86163068-bd9dde00-badd-11ea-9ad8-47f06dd4122f.jpg)

**Smartphone (please complete the following information):**
- Device: Huawei P20
- OS: Android 9.

**Comment by vpeycheva** [comment]
Just as a note, this occurs only on mobile. The web application does not have such a problem.

**Comment by Viktoriia-Chumak** [comment]
That is why phone and OS are specified in the device field in this report, which would be incorrect for report for the web version.
The web version of the application has a slightly different look of this field)

**Comment by duy-a** [comment]
fix has been released for the android
