### ISSUE TITLE
Added category isn't been displayed in menu

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#29]
**Describe the bug**
New category isn't been displayed in menu after adding to Categories. There are only 2 categories in menu which is related to tasks. The same situation with tags.

**To Reproduce**
1. Open app
2. Press settings button on section 'Categories'
3. Hide the panel to watch sorted tasks
4. Press 'Add'
5. Fill in category's name
6. Press 'Save'
7. Slide from the left to the right to open menu
8. Open section 'Categories'
9. There are only 2 categories inside

**Expected behavior**
All categories should been displayed inside 'Category' section in menu no matter if they have related tasks or not.

**Screenshots**
![1](https://user-images.githubusercontent.com/65408344/86167638-e7a6ce80-bae4-11ea-9eff-71355edfbb59.jpg)
![2](https://user-images.githubusercontent.com/65408344/86167641-e83f6500-bae4-11ea-994e-4c763a0c77ef.jpg)
![3](https://user-images.githubusercontent.com/65408344/86167643-e83f6500-bae4-11ea-9f10-e9378edccae8.jpg)
![4](https://user-images.githubusercontent.com/65408344/86167644-e8d7fb80-bae4-11ea-846b-01e3303ae72a.jpg)

**Smartphone (please complete the following information):**
- Device: Huawei P20
- OS: Android 9.

**Comment by vpeycheva** [comment]
I believe a category is only visible if it currently in use in at least 1 task.

**Comment by duy-a** [comment]
Only the categories with the **open** tasks will be displayed on the side bar. The number in brackets displays the number of open tasks.

The same applies to the tags.

Open to suggestions how to make it clearer.

**Comment by Viktoriia-Chumak** [comment]
In this case, you can rename the section to 'Categories in use' or 'Tags in use' to make it clearer why not all categories are displayed.
Or display all categories with the number of tasks in brackets, even if the number of tasks is zero.

**Comment by vpeycheva** [comment]
I think that is not necessary, because tags and categories are there to help you filter specific tasks. You can easily see them all in tags and category settings. And there is no need to see them all, because the autofill suggestion function prevents duplication.
