### ISSUE TITLE
Wrong redirecting to 'All todos' section after creating and closing tasks in 'Week planning' section

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#30]
**Describe the bug**
There is wrong behavior of the program after creating and closing tasks in 'Week planning' section. User is redirected to 'All todos' page after closing new task.  But if user opens task that is created earlier and closes this task, user will stay in page 'Week planning'.

**To Reproduce**
1. Open app
2. Open 'Week planning'
3. Choose day (Thursday 02/07/2020)
4. Press '+'
5. Create new task and set notification time
6. Save and close task
7. Now I am redirected to 'All todos' section but should be in 'Week planning'

**Expected behavior**
User should stay in page 'Week planning' page after creating and closing tasks in 'Week planning' section.

**Screenshots**
![step1](https://user-images.githubusercontent.com/65408344/86171462-c21cc380-baea-11ea-9682-c5decdd74403.jpg)
![step2](https://user-images.githubusercontent.com/65408344/86171463-c2b55a00-baea-11ea-8764-b6feea32e407.jpg)
![step3](https://user-images.githubusercontent.com/65408344/86171465-c2b55a00-baea-11ea-89c3-6fd47c0f0f8a.jpg)
![step4](https://user-images.githubusercontent.com/65408344/86171466-c34df080-baea-11ea-9342-7f0d051aeecc.jpg)

**Smartphone (please complete the following information):**
- Device: Huawei P20
- OS: Android 9.

**Comment by duy-a** [comment]
now redirecting to corresponding date. 

If no due date is available, will be redirected to "Inbox"
