### ISSUE TITLE
Back navigation button doesn't close the program

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#5]
**Describe the bug**
Home and switch apps navigation buttons work correct in the game, but back button does not close the program. It only gets back all the steps which were made in the program. It is possible to leave the program only  pressing Home navigation button.

**To Reproduce**
1) Open the program
2) Open 'Menu' 
3) Choose 'Today'
4) Press back button (this action returns user to the Inbox page)
5) Press back button to close the program
4) Nothing happens

**Expected behavior**
Back navigation button should close the program after  getting back all the steps which were made in the program.

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - OS: Android 9.0

**Comment by duy-a** [comment]
Has been fixed in the current open beta android version:

You can now exit the app by pressing the back button triple times

**Comment by Viktoriia-Chumak** [comment]
It works.
