### ISSUE TITLE
Presence of left side panel on the screen after sorting tasks by tags

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#6]
**Describe the bug**
There is problem with automatic hiding of side panel. Left side panel with menu should hides automatically after sorting task by tags. But it stays open.  

**To Reproduce**
1) Open a program
2) Slide from the left to the right to open menu
3) Choose one of the tags to sort tasks
4) Tasks are sorted, but side panel with menu didn't hide automatically 
5) Slide from the right to the left to hide the panel to watch sorted tasks

**Expected behavior**
Left side panel with menu should hides automatically after sorting task by tags.

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - OS: Android 9.
![Screenshot_20200511_133415_io tobidun app](https://user-images.githubusercontent.com/65408344/82261621-5cef8300-992d-11ea-923e-b4a9ca605cfe.jpg)
![Screenshot_20200511_133641_io tobidun app](https://user-images.githubusercontent.com/65408344/82261623-5d881980-992d-11ea-88ea-0eefff1d7cc3.jpg)

0

**Comment by duy-a** [comment]
has been fixed in the current open beta version

**Comment by Viktoriia-Chumak** [comment]
It isn't fixed

**Comment by duy-a** [comment]
have released a hot fix, update should be available via google play store soon.

**Comment by Viktoriia-Chumak** [comment]
It works correct.
