### ISSUE TITLE
Problem with sorting tasks after adding

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#8]
![step1](https://user-images.githubusercontent.com/65408344/82262384-d176f180-992e-11ea-909b-03c9a6317e0b.jpg)
![step2](https://user-images.githubusercontent.com/65408344/82262387-d20f8800-992e-11ea-9237-423d4594fa1d.jpg)
![step3](https://user-images.githubusercontent.com/65408344/82262389-d20f8800-992e-11ea-9068-f8f21291b50b.jpg)
![step4](https://user-images.githubusercontent.com/65408344/82262390-d2a81e80-992e-11ea-8760-38e5a5771452.jpg)

**Describe the bug**
There is no logical order with sorting new tasks after adding into 'Today" folder. Task are sorted without clear rules. But in 'All todos' folder tasks are sorted by  time of addition.

**To Reproduce**
1) Open program
2) Press '+' in Inbox page
3) Add new task for today and save it
4) Repeat this action few times (with different time of notification for today)
5) Open 'Today' folder in page 'In progress'
  
**Expected behavior**
Tasks should be sorted by some condition (time of addition, time of notification, tag or ascending/descending order)

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - OS: Android 9.0

**Comment by duy-a** [comment]
Will not be fixed, the next release will have a redesign of the filters.

Please take note that the alpha version version with the redesign has been deployed to https://app.tododone.io as well as on android. 

The email with the release has been sent as well
